import logging
from typing import Dict, Any

logger = logging.getLogger(__name__)

def render_technical_commentary(data: Dict[str, Any]) -> str:
    \"\"\"
    Renders the technical commentary data into a professional Telegram message.
    Presentation V2: Focused on clarity, professional terminology and structured layout.
    \"\"\"
    try:
        symbol = data.get('symbol', 'Unknown')
        commentary = data.get('commentary', {})
        
        # Header
        message = f"?? *Technical Analysis: {symbol}*\n"
        message += "¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦\n\n"
        
        # Section 1: Market Regime & Trend
        message += "?? *Market Context*\n"
        regime = commentary.get('regime', 'N/A')
        trend = commentary.get('trend', 'N/A')
        message += f"• Regime: {regime}\n"
        message += f"• Trend: {trend}\n\n"
        
        # Section 2: Key Technical Features (Semantic V2)
        message += "?? *Technical Features*\n"
        features = commentary.get('features', {})
        for feature, status in features.items():
            # Clean up feature name for display
            display_name = feature.replace('_', ' ').capitalize()
            message += f"• {display_name}: {status}\n"
        
        message += "\n"
        
        # Section 3: Detailed Commentary
        message += "?? *Analyst Commentary*\n"
        summary = commentary.get('summary', 'No summary available.')
        message += f"_{summary}_\n\n"
        
        message += "¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦\n"
        message += "?? _Generated by Technical Telegram Bot_"
        
        return message
    except Exception as e:
        logger.error(f"Error rendering commentary: {e}")
        return "? Error generating technical report."

if __name__ == '__main__':
    # Quick test
    test_data = {
        'symbol': 'AAPL',
        'commentary': {
            'regime': 'Bullish',
            'trend': 'Strong Up',
            'features': {'momentum': 'Positive', 'volatility': 'Low', 'volume': 'Increasing'},
            'summary': 'Stock is showing strong upward momentum with decreasing volatility, confirming a healthy trend.'
        }
    }
    print(render_technical_commentary(test_data))
